apiVersion: v1
kind: ConfigMap
metadata:
  name: log-parser
  namespace: efk
data:
  fluentd.conf: |

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>
    <match kubernetes.var.log.containers.**kube-system**.log>                                                                            
      @type null
    </match>
    <match kubernetes.var.log.containers.**istio-system**.log>
      @type null
    </match>
    <match kubernetes.var.log.containers.**kube-node-lease**.log>
      @type null
    </match>
    <match kubernetes.var.log.containers.**kube-public**.log>
      @type null
    </match>
    <match kubernetes.var.log.containers.**efk**.log>
      @type null
    </match>
    <match kubernetes.var.log.containers.**default**.log>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Get the logs from the containers running in the cluster
    # This block parses logs using an expression valid for the Apache log format
    # Update this depending on your application log format
    <source>
      @type tail
      path /var/log/containers/*.log
      exclude_path /var/log/containers/*efk*.log
      exclude_path /var/log/containers/*default*.log
      exclude_path /var/log/containers/*istio-system*.log
      exclude_path /var/log/containers/*kube-node-lease*.log
      exclude_path /var/log/containers/*kube-public*.log
      exclude_path /var/log/containers/*kube-system*.log
      pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
      tag www.log
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    # Forward all logs to the aggregators
    <match **>
      @type forward
      <server>
        host fluentd-0.fluentd-headless.efk.svc.cluster.local
        port 24224
      </server>

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
